USE [master]
GO
/****** Object:  Database [dboEasyReserve]    Script Date: 11/11/2023 04:24:47 a. m. ******/
CREATE DATABASE [dboEasyReserve]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'dboEasyReserve', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\dboEasyReserve.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'dboEasyReserve_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\dboEasyReserve_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [dboEasyReserve] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [dboEasyReserve].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [dboEasyReserve] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [dboEasyReserve] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [dboEasyReserve] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [dboEasyReserve] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [dboEasyReserve] SET ARITHABORT OFF 
GO
ALTER DATABASE [dboEasyReserve] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [dboEasyReserve] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [dboEasyReserve] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [dboEasyReserve] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [dboEasyReserve] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [dboEasyReserve] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [dboEasyReserve] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [dboEasyReserve] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [dboEasyReserve] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [dboEasyReserve] SET  DISABLE_BROKER 
GO
ALTER DATABASE [dboEasyReserve] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [dboEasyReserve] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [dboEasyReserve] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [dboEasyReserve] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [dboEasyReserve] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [dboEasyReserve] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [dboEasyReserve] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [dboEasyReserve] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [dboEasyReserve] SET  MULTI_USER 
GO
ALTER DATABASE [dboEasyReserve] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [dboEasyReserve] SET DB_CHAINING OFF 
GO
ALTER DATABASE [dboEasyReserve] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [dboEasyReserve] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [dboEasyReserve] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [dboEasyReserve] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [dboEasyReserve] SET QUERY_STORE = ON
GO
ALTER DATABASE [dboEasyReserve] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [dboEasyReserve]
GO
/****** Object:  Table [dbo].[tblLogin]    Script Date: 11/11/2023 04:24:48 a. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tblLogin](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[strUsuario] [varchar](50) NULL,
	[strContrasena] [varchar](50) NULL,
 CONSTRAINT [PK_tblLogin] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET IDENTITY_INSERT [dbo].[tblLogin] ON 
GO
INSERT [dbo].[tblLogin] ([ID], [strUsuario], [strContrasena]) VALUES (1, N'Admin', N'Admin')
GO
SET IDENTITY_INSERT [dbo].[tblLogin] OFF
GO
USE [master]
GO
ALTER DATABASE [dboEasyReserve] SET  READ_WRITE 
GO
